"use strict";

//database
const fiveStars = {
  Admiral_Serena: [
    ["Huge Hellaloya", "Mad Jackson"],
    ["Mad Jackson", "Cao Cao"],
    ["Mad Jackson", "Eric"],
    ["Mad Jackson", "Ninja"],
    ["Mad Jackson", "Sakura"],
    ["Mad Jackson", "Zhuge Liang"]
  ],
  Alpaco: [
    ["Aaron", "Walking Skeleton"],
    ["Bad Vlad", "Monkey King"],
    ["Demon Boy", "Monkey King"],
    ["Demon Boy", "Walking Skeleton"],
    ["Giant Slime", "Demon Boy"],
    ["Giant Slime", "Easter Bunny"],
    ["Giant Slime", "Ennui"],
    ["Giant Slime", "Mr Old"],
    ["Henry", "Walking Skeleton"],
    ["Masky Lia", "Easter Bunny"],
    ["Monkey King", "Easter Bunny"],
    ["Mr Alan", "Easter Bunny"],
    ["Orc", "Demon Boy"],
    ["Orc", "Easter Bunny"],
    ["Stove Tops", "Monkey King"],
    ["Tin Man", "Tripod"],
    ["Tripod", "Golden Troop"],
    ["Tripod", "Snow Joe"],
    ["Walking Skeleton", "Easter Bunny"]
  ],
  Angel: [
    ["Aaron", "Abbie"],
    ["Aaron", "Barot"],
    ["Aaron", "Dong Zhuo"],
    ["Aaron", "Easter Bunny"],
    ["Aaron", "Ninja"],
    ["Aaron", "Zhuge Liang"],
    ["Bad Vlad", "Kingpin"],
    ["Barot", "Bad Vlad"],
    ["Barot", "Witch"],
    ["Dr Sera", "Bad Vlad"],
    ["Dr Sera", "Mr She"],
    ["Dr Sera", "Witch"],
    ["Ennui", "Elf"],
    ["Ennui", "Zhuge Liang"],
    ["Foxy Girl", "Henry"],
    ["Foxy Girl", "Mr Cray"],
    ["Foxy Girl", "Walking Skeleton"],
    ["Geeky Vincent", "Aaron"],
    ["Giant Slime", "Sie"],
    ["Henry", "Easter Bunny"],
    ["Mcdonalds", "Mr Cray"],
    ["Medusa", "Stove Tops"],
    ["Mr Alan", "Monkey King"],
    ["Mr Alan", "Zhuge Liang"],
    ["Mr Cray", "Assassin alien"],
    ["Mr Old", "Elf"],
    ["Mr She", "Barot"],
    ["Mr She", "Kingpin"],
    ["Mr She", "Mad Jackson"],
    ["Ponytail Alien", "Kingpin"],
    ["Sie", "Aaron"],
    ["Sie", "Assassin alien"],
    ["Sie", "Bad Vlad"],
    ["Sie", "Mr She"],
    ["Sie", "Witch"],
    ["Stevo", "Bad Vlad"],
    ["Stevo", "Mr She"],
    ["Stevo", "Witch"],
    ["Stove Tops", "Aaron"],
    ["Stove Tops", "Bad Vlad"],
    ["Stove Tops", "Mr She"],
    ["Stove Tops", "Witch"],
    ["Witch", "Kingpin"]
  ],
  Aquarius: [
    ["Assassin alien", "Server Eric"],
    ["Barot", "Elf"],
    ["Barot", "Ennui"],
    ["Barot", "Server Eric"],
    ["Bliss", "Ninja"],
    ["Demon Boy", "Server Eric"],
    ["Demon Boy", "Witch"],
    ["Dr Sera", "Abbie"],
    ["Dr Sera", "Dong Zhuo"],
    ["Foxy Girl", "Bliss"],
    ["Foxy Girl", "Mr Alan"],
    ["Geeky Vincent", "Henry"],
    ["Geeky Vincent", "Kingpin"],
    ["Geeky Vincent", "Server Eric"],
    ["Henry", "Bad Vlad"],
    ["Henry", "Witch"],
    ["Huge Hellaloya", "Abbie"],
    ["Huge Hellaloya", "Dong Zhuo"],
    ["Huge Hellaloya", "Monkey King"],
    ["Mcdonalds", "Assassin alien"],
    ["Medusa", "Kingpin"],
    ["Mr Cray", "Aaron"],
    ["Mr Cray", "Bad Vlad"],
    ["Mr Cray", "Monkey King"],
    ["Mr Cray", "Witch"],
    ["Mr She", "Henry"],
    ["Mr She", "Mr Cray"],
    ["Ron", "Walking Skeleton"],
    ["Sie", "Ennui"],
    ["Sie", "Server Eric"],
    ["Stevo", "Demon Boy"],
    ["Stevo", "Ninja"],
    ["Stevo", "Ponytail Alien"],
    ["Stove Tops", "Ennui"],
    ["Stove Tops", "Mad Jackson"],
    ["Stove Tops", "Server Eric"]
  ],
  Aries: [
    ["Aaron", "Bliss"],
    ["Aaron", "Mad Jackson"],
    ["Barot", "Walking Skeleton"],
    ["Bliss", "Teddy"],
    ["Dr Sera", "Mcdonalds"],
    ["Ennui", "Ninja"],
    ["Giant Slime", "Huge Hellaloya"],
    ["Giant Slime", "Mr Cray"],
    ["Henry", "Ennui"],
    ["Henry", "Server Eric"],
    ["Mcdonalds", "Kingpin"],
    ["Mr Alan", "Aaron"],
    ["Mr Cray", "Ardent Templar"],
    ["Orc", "Bliss"],
    ["Ron", "Assassin alien"],
    ["Server Eric", "Easter Bunny"],
    ["Sie", "Ardent Templar"],
    ["Stevo", "Easter Bunny"],
    ["Stevo", "Mcdonalds"],
    ["Witch", "Easter Bunny"]
  ],
  Bogan: [
    ["Aaron", "Kingpin"],
    ["Assassin alien", "Bliss"],
    ["Bad Vlad", "Cao Cao"],
    ["Bad Vlad", "Easter Bunny"],
    ["Bad Vlad", "Sakura"],
    ["Barot", "Cao Cao"],
    ["Barot", "Mad Jackson"],
    ["Barot", "Ninja"],
    ["Barot", "Sakura"],
    ["Bliss", "Liu Bei"],
    ["Dr Sera", "Aaron"],
    ["Dr Sera", "Mad Jackson"],
    ["Ennui", "Bliss"],
    ["Ennui", "Mad Jackson"],
    ["Foxy Girl", "Cao Cao"],
    ["Foxy Girl", "Keira"],
    ["Foxy Girl", "Ninja"],
    ["Foxy Girl", "Orc"],
    ["Foxy Girl", "Sakura"],
    ["Foxy Girl", "Teddy"],
    ["Golden Boy", "Mr She"],
    ["Golden Boy", "Ron"],
    ["Henry", "TJ"],
    ["Keira", "Bad Vlad"],
    ["Keira", "Barot"],
    ["Keira", "Mr She"],
    ["Keira", "Witch"],
    ["Masky Lia", "Mr She"],
    ["Mcdonalds", "Henry"],
    ["Mcdonalds", "Monkey King"],
    ["Medusa", "Aaron"],
    ["Mr Alan", "Ennui"],
    ["Mr Alan", "Mad Jackson"],
    ["Mr Alan", "Server Eric"],
    ["Mr Alan", "TJ"],
    ["Mr Alan", "Walking Skeleton"],
    ["Mr Cray", "Eric"],
    ["Mr Cray", "Liu Bei"],
    ["Mr She", "Cao Cao"],
    ["Mr She", "Golden Troop"],
    ["Mr She", "Monkey King"],
    ["Mr She", "Ninja"],
    ["Mr She", "Sakura"],
    ["Mr She", "Snow Joe"],
    ["Ninja", "Witch"],
    ["Ron", "Eric"],
    ["Ron", "Golden Troop"],
    ["Ron", "Liu Bei"],
    ["Ron", "Masky Lia"],
    ["Ron", "Ponytail Alien"],
    ["Ron", "Snow Joe"],
    ["Sakura", "Witch"],
    ["Server Eric", "Bliss"],
    ["Sie", "Agay"],
    ["Sie", "Geeky Vincent"],
    ["Sie", "Zhao Yun"],
    ["Stevo", "Aaron"],
    ["Stevo", "Ardent Templar"],
    ["Stevo", "Liu Bei"],
    ["Stove Tops", "Easter Bunny"],
    ["Stove Tops", "TJ"],
    ["TJ", "Kingpin"],
    ["TJ", "Server Eric"],
    ["Witch", "Cao Cao"]
  ],
  Cancer: [
    ["Aaron", "Elf"],
    ["Agay", "Stove Tops"],
    ["Ardent Templar", "Server Eric"],
    ["Bad Vlad", "Assassin alien"],
    ["Bad Vlad", "Eric"],
    ["Bad Vlad", "Liu Bei"],
    ["Bad Vlad", "Teddy"],
    ["Barot", "Eric"],
    ["Barot", "Liu Bei"],
    ["Bliss", "Cao Cao"],
    ["Dr Sera", "Huge Hellaloya"],
    ["Dr Sera", "TJ"],
    ["Ennui", "Monkey King"],
    ["Eric", "Witch"],
    ["Foxy Girl", "Assassin alien"],
    ["Foxy Girl", "Eric"],
    ["Foxy Girl", "Liu Bei"],
    ["Giant Slime", "Foxy Girl"],
    ["Henry", "Assassin alien"],
    ["Henry", "Elf"],
    ["Huge Hellaloya", "Aaron"],
    ["Huge Hellaloya", "Bliss"],
    ["Huge Hellaloya", "Ennui"],
    ["Huge Hellaloya", "Henry"],
    ["Huge Hellaloya", "Huge Hellaloya"],
    ["Huge Hellaloya", "Kingpin"],
    ["Huge Hellaloya", "Mr Alan"],
    ["Huge Hellaloya", "Server Eric"],
    ["Huge Hellaloya", "TJ"],
    ["Keira", "Bliss"],
    ["Keira", "Mr Cray"],
    ["Mcdonalds", "Ardent Templar"],
    ["Mcdonalds", "Huge Hellaloya"],
    ["Mr Alan", "Demon Boy"],
    ["Mr Cray", "Cao Cao"],
    ["Mr Cray", "Ninja"],
    ["Mr Cray", "Sakura"],
    ["Mr Old", "Assassin alien"],
    ["Mr Old", "Monkey King"],
    ["Mr She", "Eric"],
    ["Mr She", "Liu Bei"],
    ["Orc", "Bad Vlad"],
    ["Orc", "Stove Tops"],
    ["Ponytail Alien", "Bliss"],
    ["Ron", "Cao Cao"],
    ["Ron", "Keira"],
    ["Ron", "Ninja"],
    ["Ron", "Sakura"],
    ["Sie", "Abbie"],
    ["Sie", "Dong Zhuo"],
    ["Sie", "Easter Bunny"],
    ["Sie", "TJ"],
    ["Stevo", "Cao Cao"],
    ["Stevo", "Huge Hellaloya"],
    ["Stevo", "Keira"],
    ["Stove Tops", "Teddy"],
    ["Stove Tops", "Zhao Yun"],
    ["TJ", "Ennui"],
    ["Walking Skeleton", "Kingpin"],
    ["Witch", "Liu Bei"]
  ],
  Capricorn: [
    ["Abbie", "Elf"],
    ["Abbie", "Walking Skeleton"],
    ["Ardent Templar", "Elf"],
    ["Ardent Templar", "Teddy"],
    ["Barot", "Easter Bunny"],
    ["Demon Boy", "Cao Cao"],
    ["Demon Boy", "Ninja"],
    ["Demon Boy", "Sakura"],
    ["Elf", "Dong Zhuo"],
    ["Eric", "Easter Bunny"],
    ["Eric", "Monkey King"],
    ["Giant Slime", "Golden Boy"],
    ["Golden Boy", "Teddy"],
    ["Huge Hellaloya", "Elf"],
    ["Keira", "Demon Boy"],
    ["Keira", "Teddy"],
    ["Keira", "Tripod"],
    ["Liu Bei", "Easter Bunny"],
    ["Mad Jackson", "Walking Skeleton"],
    ["Monkey King", "Liu Bei"],
    ["Monkey King", "Witch"],
    ["Mr Cray", "Elf"],
    ["Ninja", "Teddy"],
    ["Orc", "Eric"],
    ["Orc", "Liu Bei"],
    ["Orc", "Mad Jackson"],
    ["Ponytail Alien", "Elf"],
    ["Ponytail Alien", "Teddy"],
    ["Sakura", "Teddy"],
    ["Server Eric", "Monkey King"],
    ["Stevo", "Monkey King"],
    ["TJ", "Elf"],
    ["TJ", "Walking Skeleton"],
    ["Teddy", "Cao Cao"],
    ["Tripod", "Ardent Templar"],
    ["Tripod", "Cao Cao"],
    ["Tripod", "Ninja"],
    ["Tripod", "Ponytail Alien"],
    ["Tripod", "Sakura"],
    ["Walking Skeleton", "Dong Zhuo"]
  ],
  Gemini: [
    ["Aaron", "Ardent Templar"],
    ["Abbie", "Kingpin"],
    ["Abbie", "Server Eric"],
    ["Bad Vlad", "Ennui"],
    ["Bad Vlad", "Golden Troop"],
    ["Bad Vlad", "Server Eric"],
    ["Bad Vlad", "Snow Joe"],
    ["Barot", "Barot"],
    ["Barot", "Kingpin"],
    ["Demon Boy", "Kingpin"],
    ["Dr Sera", "Barot"],
    ["Dr Sera", "Geeky Vincent"],
    ["Dr Sera", "Sie"],
    ["Dr Sera", "Stove Tops"],
    ["Ennui", "Witch"],
    ["Foxy Girl", "Foxy Girl"],
    ["Foxy Girl", "Mcdonalds"],
    ["Geeky Vincent", "Huge Hellaloya"],
    ["Giant Slime", "Bad Vlad"],
    ["Giant Slime", "Stove Tops"],
    ["Golden Boy", "Bad Vlad"],
    ["Golden Boy", "Mr Cray"],
    ["Golden Boy", "Witch"],
    ["Henry", "Abbie"],
    ["Henry", "Dong Zhuo"],
    ["Kingpin", "Dong Zhuo"],
    ["Masky Lia", "Bad Vlad"],
    ["Masky Lia", "Mr Cray"],
    ["Masky Lia", "Witch"],
    ["Mcdonalds", "Elf"],
    ["Medusa", "Huge Hellaloya"],
    ["Mr Alan", "Mr Cray"],
    ["Mr Cray", "Bliss"],
    ["Mr Cray", "Golden Troop"],
    ["Mr Cray", "Ponytail Alien"],
    ["Mr Cray", "Snow Joe"],
    ["Mr She", "Elf"],
    ["Mr She", "Ennui"],
    ["Mr She", "Server Eric"],
    ["Orc", "Sie"],
    ["Server Eric", "Dong Zhuo"],
    ["Server Eric", "Witch"],
    ["Sie", "Barot"],
    ["Sie", "Kingpin"],
    ["Sie", "Ponytail Alien"],
    ["Sie", "Sie"],
    ["Sie", "Stove Tops"],
    ["Sie", "Teddy"],
    ["Snow Joe", "Witch"],
    ["Stevo", "Assassin alien"],
    ["Stevo", "Barot"],
    ["Stevo", "Sie"],
    ["Stevo", "Stove Tops"],
    ["Stove Tops", "Barot"],
    ["Stove Tops", "Kingpin"],
    ["Stove Tops", "Stove Tops"],
    ["Witch", "Golden Troop"]
  ],
  Green_Ranger_Oliver: [
    ["Aaron", "Cao Cao"],
    ["Aaron", "Liu Bei"],
    ["Aaron", "Mistycball"],
    ["Aaron", "TJ"],
    ["Agay", "Mr Old"],
    ["Ardent Templar", "Witch"],
    ["Assassin alien", "Witch"],
    ["Bad Uncle", "Aaron"],
    ["Bad Uncle", "Bad Vlad"],
    ["Bad Uncle", "Barot"],
    ["Bad Uncle", "Bliss"],
    ["Bad Uncle", "Ennui"],
    ["Bad Uncle", "Henry"],
    ["Bad Uncle", "Huge Hellaloya"],
    ["Bad Uncle", "Kingpin"],
    ["Bad Uncle", "Mcdonalds"],
    ["Bad Uncle", "Mr Alan"],
    ["Bad Uncle", "Mr Cray"],
    ["Bad Uncle", "Mr Old"],
    ["Bad Uncle", "Mr She"],
    ["Bad Uncle", "Server Eric"],
    ["Bad Uncle", "Stove Tops"],
    ["Bad Uncle", "Witch"],
    ["Bad Vlad", "Government Troop"],
    ["Bad Vlad", "Zhang Fei"],
    ["Barot", "Golden Troop"],
    ["Barot", "Government Troop"],
    ["Barot", "Mistycball"],
    ["Barot", "Snow Joe"],
    ["Barot", "Zhang Fei"],
    ["Barot", "Zhuge Liang"],
    ["Dr Sera", "Bad Uncle"],
    ["Dr Sera", "Le Vincent"],
    ["Dr Sera", "Mistycball"],
    ["Dr Sera", "Mr Old"],
    ["Dr Sera", "Ron"],
    ["Dr Sera", "Tripod"],
    ["Foxy Girl", "Bad Uncle"],
    ["Foxy Girl", "Golden Troop"],
    ["Foxy Girl", "Government Troop"],
    ["Foxy Girl", "Huge Hellaloya"],
    ["Foxy Girl", "Le Vincent"],
    ["Foxy Girl", "Masky Lia"],
    ["Foxy Girl", "Mistycball"],
    ["Foxy Girl", "Mr Old"],
    ["Foxy Girl", "Ron"],
    ["Foxy Girl", "Snow Joe"],
    ["Foxy Girl", "Tripod"],
    ["Foxy Girl", "Zhang Fei"],
    ["Foxy Girl", "Zhuge Liang"],
    ["Golden Boy", "Barot"],
    ["Golden Boy", "Foxy Girl"],
    ["Golden Boy", "Mr Old"],
    ["Golden Boy", "Sie"],
    ["Golden Boy", "Stove Tops"],
    ["Government Troop", "Witch"],
    ["Henry", "Mistycball"],
    ["Huge Hellaloya", "Bad Vlad"],
    ["Huge Hellaloya", "Barot"],
    ["Huge Hellaloya", "Mistycball"],
    ["Huge Hellaloya", "Mr Cray"],
    ["Huge Hellaloya", "Mr Old"],
    ["Huge Hellaloya", "Mr She"],
    ["Huge Hellaloya", "Tripod"],
    ["Huge Hellaloya", "Witch"],
    ["Keira", "Aaron"],
    ["Keira", "Mr Old"],
    ["Le Vincent", "Aaron"],
    ["Le Vincent", "Bad Vlad"],
    ["Le Vincent", "Barot"],
    ["Le Vincent", "Bliss"],
    ["Le Vincent", "Ennui"],
    ["Le Vincent", "Henry"],
    ["Le Vincent", "Huge Hellaloya"],
    ["Le Vincent", "Kingpin"],
    ["Le Vincent", "Mcdonalds"],
    ["Le Vincent", "Mr Alan"],
    ["Le Vincent", "Mr Cray"],
    ["Le Vincent", "Mr Old"],
    ["Le Vincent", "Mr She"],
    ["Le Vincent", "Server Eric"],
    ["Le Vincent", "Stove Tops"],
    ["Le Vincent", "Witch"],
    ["Mad Jackson", "Witch"],
    ["Masky Lia", "Barot"],
    ["Masky Lia", "Mr Old"],
    ["Mcdonalds", "Cao Cao"],
    ["Mcdonalds", "Keira"],
    ["Mcdonalds", "Liu Bei"],
    ["Mcdonalds", "Mistycball"],
    ["Mcdonalds", "Mr Old"],
    ["Mcdonalds", "TJ"],
    ["Mcdonalds", "Tripod"],
    ["Medusa", "Witch"],
    ["Mistycball", "Bad Vlad"],
    ["Mistycball", "Bliss"],
    ["Mistycball", "Ennui"],
    ["Mistycball", "Kingpin"],
    ["Mistycball", "Server Eric"],
    ["Mistycball", "Witch"],
    ["Mr Alan", "Mistycball"],
    ["Mr Cray", "Government Troop"],
    ["Mr Cray", "Mistycball"],
    ["Mr Cray", "Zhang Fei"],
    ["Mr Cray", "Zhuge Liang"],
    ["Mr Old", "Aaron"],
    ["Mr Old", "Bad Vlad"],
    ["Mr Old", "Barot"],
    ["Mr Old", "Bliss"],
    ["Mr Old", "Cao Cao"],
    ["Mr Old", "Ennui"],
    ["Mr Old", "Eric"],
    ["Mr Old", "Golden Troop"],
    ["Mr Old", "Government Troop"],
    ["Mr Old", "Henry"],
    ["Mr Old", "Kingpin"],
    ["Mr Old", "Liu Bei"],
    ["Mr Old", "Mistycball"],
    ["Mr Old", "Mr Alan"],
    ["Mr Old", "Mr Cray"],
    ["Mr Old", "Mr Old"],
    ["Mr Old", "Sakura"],
    ["Mr Old", "Server Eric"],
    ["Mr Old", "Snow Joe"],
    ["Mr Old", "TJ"],
    ["Mr Old", "Witch"],
    ["Mr Old", "Zhang Fei"],
    ["Mr Old", "Zhao Yun"],
    ["Mr She", "Government Troop"],
    ["Mr She", "Mistycball"],
    ["Mr She", "Mr Old"],
    ["Mr She", "Zhang Fei"],
    ["Mr She", "Zhuge Liang"],
    ["Ponytail Alien", "Witch"],
    ["Ron", "Aaron"],
    ["Ron", "Bad Uncle"],
    ["Ron", "Bad Vlad"],
    ["Ron", "Barot"],
    ["Ron", "Bliss"],
    ["Ron", "Ennui"],
    ["Ron", "Government Troop"],
    ["Ron", "Henry"],
    ["Ron", "Huge Hellaloya"],
    ["Ron", "Kingpin"],
    ["Ron", "Le Vincent"],
    ["Ron", "Mcdonalds"],
    ["Ron", "Mistycball"],
    ["Ron", "Mr Alan"],
    ["Ron", "Mr Cray"],
    ["Ron", "Mr Old"],
    ["Ron", "Mr She"],
    ["Ron", "Ron"],
    ["Ron", "Server Eric"],
    ["Ron", "Sie"],
    ["Ron", "Stevo"],
    ["Ron", "Stove Tops"],
    ["Ron", "Tripod"],
    ["Ron", "Witch"],
    ["Ron", "Zhang Fei"],
    ["Ron", "Zhuge Liang"],
    ["Sie", "Bad Uncle"],
    ["Sie", "Golden Troop"],
    ["Sie", "Government Troop"],
    ["Sie", "Huge Hellaloya"],
    ["Sie", "Le Vincent"],
    ["Sie", "Masky Lia"],
    ["Sie", "Mistycball"],
    ["Sie", "Mr Old"],
    ["Sie", "Snow Joe"],
    ["Sie", "Tripod"],
    ["Sie", "Zhang Fei"],
    ["Sie", "Zhuge Liang"],
    ["Stevo", "Bad Uncle"],
    ["Stevo", "Le Vincent"],
    ["Stevo", "Mistycball"],
    ["Stevo", "Mr Old"],
    ["Stevo", "Tripod"],
    ["Stove Tops", "Golden Troop"],
    ["Stove Tops", "Government Troop"],
    ["Stove Tops", "Huge Hellaloya"],
    ["Stove Tops", "Masky Lia"],
    ["Stove Tops", "Mistycball"],
    ["Stove Tops", "Mr Old"],
    ["Stove Tops", "Snow Joe"],
    ["Stove Tops", "Tripod"],
    ["Stove Tops", "Zhang Fei"],
    ["Tin Man", "Bad Vlad"],
    ["Tin Man", "Barot"],
    ["Tin Man", "Foxy Girl"],
    ["Tin Man", "Mr Cray"],
    ["Tin Man", "Mr Old"],
    ["Tin Man", "Mr She"],
    ["Tin Man", "Ron"],
    ["Tin Man", "Sie"],
    ["Tin Man", "Stove Tops"],
    ["Tin Man", "Witch"],
    ["Tripod", "Aaron"],
    ["Tripod", "Bad Vlad"],
    ["Tripod", "Barot"],
    ["Tripod", "Bliss"],
    ["Tripod", "Ennui"],
    ["Tripod", "Henry"],
    ["Tripod", "Kingpin"],
    ["Tripod", "Mr Alan"],
    ["Tripod", "Mr Cray"],
    ["Tripod", "Mr Old"],
    ["Tripod", "Mr She"],
    ["Tripod", "Server Eric"],
    ["Tripod", "Witch"],
    ["Witch", "Zhang Fei"],
    ["Witch", "Zhuge Liang"]
  ],
  Guan_Yu: [
    ["Abbie", "Abbie"],
    ["Abbie", "Dong Zhuo"],
    ["Abbie", "Government Troop"],
    ["Abbie", "Mad Jackson"],
    ["Abbie", "Ninja"],
    ["Abbie", "Zhuge Liang"],
    ["Agay", "Elf"],
    ["Agay", "Mad Jackson"],
    ["Agay", "Walking Skeleton"],
    ["Cao Cao", "Easter Bunny"],
    ["Demon Boy", "Eric"],
    ["Demon Boy", "Liu Bei"],
    ["Dong Zhuo", "Dong Zhuo"],
    ["Dong Zhuo", "Zhuge Liang"],
    ["Dr Sera", "Eric"],
    ["Elf", "Zhao Yun"],
    ["Ennui", "Eric"],
    ["Eric", "Teddy"],
    ["Geeky Vincent", "Abbie"],
    ["Geeky Vincent", "Bad Vlad"],
    ["Geeky Vincent", "Dong Zhuo"],
    ["Geeky Vincent", "Elf"],
    ["Geeky Vincent", "Geeky Vincent"],
    ["Geeky Vincent", "Government Troop"],
    ["Geeky Vincent", "Ninja"],
    ["Geeky Vincent", "Walking Skeleton"],
    ["Geeky Vincent", "Zhuge Liang"],
    ["Golden Boy", "Zhuge Liang"],
    ["Golden Troop", "Zhuge Liang"],
    ["Government Troop", "Dong Zhuo"],
    ["Government Troop", "Ninja"],
    ["Government Troop", "Zhuge Liang"],
    ["Henry", "Sakura"],
    ["Huge Hellaloya", "Eric"],
    ["Keira", "Easter Bunny"],
    ["Keira", "Monkey King"],
    ["Le Vincent", "Mad Jackson"],
    ["Mad Jackson", "Dong Zhuo"],
    ["Mad Jackson", "Liu Bei"],
    ["Mad Jackson", "Zhao Yun"],
    ["Masky Lia", "Zhuge Liang"],
    ["Monkey King", "Cao Cao"],
    ["Monkey King", "Sakura"],
    ["Mr Alan", "Sakura"],
    ["Ninja", "Dong Zhuo"],
    ["Ninja", "Easter Bunny"],
    ["Ninja", "Monkey King"],
    ["Ninja", "Ninja"],
    ["Ninja", "Zhuge Liang"],
    ["Orc", "Cao Cao"],
    ["Orc", "Keira"],
    ["Orc", "Ninja"],
    ["Orc", "Sakura"],
    ["Sakura", "Easter Bunny"],
    ["Sakura", "Kingpin"],
    ["Server Eric", "Sakura"],
    ["Snow Joe", "Zhuge Liang"],
    ["Stove Tops", "Ninja"],
    ["Teddy", "Liu Bei"],
    ["Tin Man", "Abbie"],
    ["Tin Man", "Dong Zhuo"],
    ["Tin Man", "Geeky Vincent"],
    ["Tin Man", "Ninja"],
    ["Tin Man", "Zhuge Liang"],
    ["Tripod", "Eric"],
    ["Tripod", "Liu Bei"],
    ["Walking Skeleton", "Zhao Yun"],
    ["Zhuge Liang", "Zhuge Liang"]
  ],
  Huntress: [
    ["Ardent Templar", "Walking Skeleton"],
    ["Bad Vlad", "Demon Boy"],
    ["Ennui", "Easter Bunny"],
    ["Giant Slime", "Aaron"],
    ["Giant Slime", "Henry"],
    ["Golden Boy", "Tripod"],
    ["Mad Jackson", "Elf"],
    ["Mad Jackson", "Teddy"],
    ["Masky Lia", "Demon Boy"],
    ["Masky Lia", "Monkey King"],
    ["Mcdonalds", "Teddy"],
    ["Mr Alan", "Elf"],
    ["Mr Old", "Easter Bunny"],
    ["Mr She", "Teddy"],
    ["Orc", "Ardent Templar"],
    ["Orc", "Mcdonalds"],
    ["Orc", "Mr She"],
    ["Orc", "Ponytail Alien"],
    ["Ponytail Alien", "Walking Skeleton"],
    ["Sie", "Walking Skeleton"],
    ["Stove Tops", "Demon Boy"],
    ["Tripod", "Mad Jackson"]
  ],
  Ichigo: [
    ["Abbie", "Snow Joe"],
    ["Agay", "Ennui"],
    ["Agay", "Huge Hellaloya"],
    ["Bad Vlad", "Ninja"],
    ["Bliss", "Eric"],
    ["Dr Sera", "Agay"],
    ["Dr Sera", "Zhao Yun"],
    ["Ennui", "Zhao Yun"],
    ["Golden Boy", "Abbie"],
    ["Golden Boy", "Dong Zhuo"],
    ["Huge Hellaloya", "Zhao Yun"],
    ["Masky Lia", "Abbie"],
    ["Masky Lia", "Dong Zhuo"],
    ["Ninja", "Golden Troop"],
    ["Snow Joe", "Dong Zhuo"],
    ["Stevo", "Eric"],
    ["Stove Tops", "Abbie"],
    ["Stove Tops", "Dong Zhuo"]
  ],
  Invader: [
    ["Abbie", "Mistycball"],
    ["Abbie", "Ponytail Alien"],
    ["Agay", "Mistycball"],
    ["Agay", "Ponytail Alien"],
    ["Ardent Templar", "Ardent Templar"],
    ["Ardent Templar", "Assassin alien"],
    ["Ardent Templar", "Demon Boy"],
    ["Ardent Templar", "Ponytail Alien"],
    ["Assassin alien", "Assassin alien"],
    ["Assassin alien", "Cao Cao"],
    ["Assassin alien", "Demon Boy"],
    ["Assassin alien", "Easter Bunny"],
    ["Assassin alien", "Elf"],
    ["Assassin alien", "Eric"],
    ["Assassin alien", "Mad Jackson"],
    ["Assassin alien", "Monkey King"],
    ["Assassin alien", "Ninja"],
    ["Assassin alien", "Ponytail Alien"],
    ["Assassin alien", "Sakura"],
    ["Assassin alien", "Teddy"],
    ["Assassin alien", "Walking Skeleton"],
    ["Assassin alien", "Zhuge Liang"],
    ["Bad Uncle", "Mistycball"],
    ["Giant Slime", "Ardent Templar"],
    ["Giant Slime", "Assassin alien"],
    ["Giant Slime", "Medusa"],
    ["Giant Slime", "Mistycball"],
    ["Giant Slime", "Ponytail Alien"],
    ["Huge Hellaloya", "Assassin alien"],
    ["Le Vincent", "Mistycball"],
    ["Le Vincent", "Ponytail Alien"],
    ["Masky Lia", "Ponytail Alien"],
    ["Medusa", "Abbie"],
    ["Medusa", "Agay"],
    ["Medusa", "Ardent Templar"],
    ["Medusa", "Assassin alien"],
    ["Medusa", "Demon Boy"],
    ["Medusa", "Dong Zhuo"],
    ["Medusa", "Easter Bunny"],
    ["Medusa", "Le Vincent"],
    ["Medusa", "Liu Bei"],
    ["Medusa", "Mad Jackson"],
    ["Medusa", "Medusa"],
    ["Medusa", "Mistycball"],
    ["Medusa", "Monkey King"],
    ["Medusa", "Mr She"],
    ["Medusa", "Ponytail Alien"],
    ["Medusa", "Zhao Yun"],
    ["Mistycball", "Ardent Templar"],
    ["Mistycball", "Assassin alien"],
    ["Mistycball", "Demon Boy"],
    ["Mistycball", "Dong Zhuo"],
    ["Mistycball", "Easter Bunny"],
    ["Mistycball", "Elf"],
    ["Mistycball", "Government Troop"],
    ["Mistycball", "Liu Bei"],
    ["Mistycball", "Mad Jackson"],
    ["Mistycball", "Mistycball"],
    ["Mistycball", "Monkey King"],
    ["Mistycball", "Ponytail Alien"],
    ["Mistycball", "Teddy"],
    ["Mistycball", "Walking Skeleton"],
    ["Mistycball", "Zhao Yun"],
    ["Orc", "Assassin alien"],
    ["Orc", "Mistycball"],
    ["Ponytail Alien", "Demon Boy"],
    ["Ponytail Alien", "Dong Zhuo"],
    ["Ponytail Alien", "Liu Bei"],
    ["Ponytail Alien", "Ponytail Alien"],
    ["Ponytail Alien", "Zhao Yun"],
    ["Stove Tops", "Ponytail Alien"],
    ["Tripod", "Assassin alien"],
    ["Tripod", "Mistycball"]
  ],
  Jaiden: [
    ["Mad Jackson", "Golden Troop"],
    ["Mad Jackson", "Mad Jackson"],
    ["Stevo", "Mad Jackson"]
  ]
};
const dbLength = Object.keys(fiveStars).length;

//UI elements
const btnOne = document.querySelector("#btnOne"),
  btnTwo = document.querySelector("#btnTwo"),
  crewOne = document.querySelector("#crewOne"),
  crewTwo = document.querySelector("#crewTwo"),
  messageOne = document.querySelector("#messageOne"),
  messageTwo = document.querySelector("#messageTwo"),
  textArea = document.querySelector("#textArea");
let firstCrew = crewOne.value.toLowerCase(),
  secondCrew = crewTwo.value.toLowerCase();

const checksForFive = () => {
  firstCrew = crewOne.value.toLowerCase();
  secondCrew = crewTwo.value.toLowerCase();
  let keyStar = "";
  for (let i = 0; i < dbLength; i++) {
    keyStar = Object.values(fiveStars)[i];
    for (let j = 0; j < keyStar.length; j++) {
      if (
        (firstCrew === Object.values(fiveStars)[i][j][0].toLowerCase() &&
          secondCrew === Object.values(fiveStars)[i][j][1].toLowerCase()) ||
        (secondCrew === Object.values(fiveStars)[i][j][0].toLowerCase() &&
          firstCrew === Object.values(fiveStars)[i][j][1].toLowerCase())
      ) {
        messageOne.innerHTML = Object.keys(fiveStars)[i];
      }
    }
  }
};

//listen for prestige
btnOne.addEventListener("click", () => {
  checksForFive();
});

crewOne.addEventListener("keyup", e => {
  if (e.keyCode == 13) {
    checksForFive();
  }
});

crewTwo.addEventListener("keyup", e => {
  if (e.keyCode == 13) {
    checksForFive();
  }
});

//export data as JSON
/* btnTwo.addEventListener("click", () => {
  const array = textArea.value.split(/\r?\n/);
  let fiveStarName = [];
  const twoCrews = [];

  fiveStarName.push(array[0]);
  array.shift();

  const fiveArray = fiveStarName[0].split(" ");
  while (fiveArray[0] === "") {
    fiveArray.shift();
  }

  fiveStarName = [];
  while (fiveArray[0] !== "can") {
    fiveStarName.push(fiveArray[0]);
    fiveArray.shift();
  }
  for (let i = 0; i < array.length; i++) {
    const removePlus = array[i].split("");
    for (let i = 0; i < removePlus.length; i++) {
      if (removePlus[i] === "+") {
        removePlus[i] = JSON.stringify(",");
        i = removePlus.length - 1;
        twoCrews.push([removePlus.join("")]);
      }
    }
  }

  messageTwo.innerHTML = ` ${fiveStarName}: ${JSON.stringify(twoCrews)}`;
  console.log(messageTwo.innerHTML);
});
 */
